### ISSUE TITLE
line 18: SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by AngelOfTerror** [SgtMalicious/FortiOS-Utilities#5]
My apologies for the mistake yesterday. This is the error for this script;
```
Y:\TEST>policy_view.py sys_config_10.36.25.9.txt

  File "Y:\TEST\policy_view.py", line 18

    raise ValueError,"missing policy information"
                    ^
SyntaxError: invalid syntax
```

This is the Python version I'm using;
`Python 3.5.0 (v3.5.0:374f501f4567, Sep 13 2015, 02:16:59) [MSC v.1900 32 bit (Intel)] on win32`

**Comment by SgtMalicious** [comment]
Sounds like Python is not recognizing sys.argv on the Windows platform. I don't use Windows so I can't say for definite if this script will execute properly on Windows, especially so since the formatting functions include color codes specific to bash. You can try checking your Windows settings for Python based on http://stackoverflow.com/questions/29540541/executable-python-script-not-take-sys-argv-in-windows but it would probably be easier to just install something like Cygwin.

**Comment by AngelOfTerror** [comment]
Thanks for the quick response.
Checked out the link, but didn't help. I've updated the script a little so that line of coding is no longer in there. 
Then I got another syntax error.

Found this site online, that can test scripts. Generates the same error as my Windows machine;
[https://repl.it/languages/python3](https://repl.it/languages/python3)

Will try Cygwin later.

**Comment by aairey** [comment]
Or try babun.github.io which makes it a whole lot easier to get a cygwin
environment running with Python support.
On 15 May 2016 17:42, "AngelOfTerror" <notifications@github.com> wrote:

Thanks for the quick response.
Checked out the link, but didn't help. I've updated the script a little so
that line of coding is no longer in there.
Then I got another syntax error.

Found this site online, that can test scripts. Generates the same error as
my Windows machine;
https://repl.it/languages/python3

Will try Cygwin later.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/SgtMalicious/FortiOS-Utilities/issues/5#issuecomment-219293043>

**Comment by SgtMalicious** [comment]
Looks like this is breakage with Python 3. Raising exceptions is syntactically different, as well as the print statements. I'll make a branch for a Python 3 version next week. You can fork the repo and make you're own changes if you like or use Python 2 instead for now.

**Comment by SgtMalicious** [comment]
Pushed a new branch that works under Python3. Clone the repo and checkout the py3_branch or download it directly.
